support github vs. python product capitalization differences
desihub/desiutil pull request #173
Opened 2021-06-03 22:34 UTC by sbailey

This PR fixes #172 by supporting installing products where the github name has a different capitalization than the python package name, e.g. https://github.com/desihub/QuasarNP hosting `quasarnp`.  Tested with
```
desiInstall -v -r $SCRATCH/desi/test QuasarNP 0.1.0
```
(that outputs to NERSC /global/cscratch1/sd/sjbailey/desi/test, but I suggest running it yourself for testing...)

2021-06-03 22:37 UTC, weaverba137 requested changes
Perhaps I caught this PR in a preliminary stage, but there's a lot left to do here.

2021-06-03 22:37 UTC, weaverba137 commented on py/desiutil/modules.py
> +         isdir(join(working_dir, product.lower())))
As I mentioned in #172, these are not the only possible combinations.  This change also needs to be applied to the case where the package lives in a `py/` directory.  Finally, we need unit tests for all of these cases.

2021-06-04 03:16 UTC, sbailey commented
I expanded a unit test for the new case where the product name is Capitalized by the python package isn't, e.g. QuasarNP/quasarnp, so these two cases are now supported and tested:
  * capitalization of the product and the python package agree (most of our products)
  * the product is Capitalized but the python package in the top level directory is all lowercase (e.g. QuasarNP/quasarnp)

However, I'm going to push back about adding support for these additional cases:
  * python package under py/ whose capitalization doesn't match the GitHub product name
  * GitHub product and python package having different capitalizations but the python package isn't entirely lower case

We don't have any cases that match either of those right now, and I don't anticipate having those cases in the future.  I suggest that this PR adds new needed functionality without breaking old functionality, even if it doesn't additionally support all possible pathological future cases.

2021-06-04 03:44 UTC, weaverba137 approved these changes

2021-06-04 03:45 UTC, weaverba137 commented
OK, I see your point.  I will merge and tag soon.

2021-06-04 03:45 UTC, merged